services:
  backend:
    build: ./backend
    container_name: chmura-backend
    networks:
      - chmura-net
  frontend:
    build: ./frontend
    container_name: chmura-frontend
    networks:
      - chmura-net
    ports:
      - 80:80
    depends_on:
      - backend
networks:
  chmura-net:
    driver: bridge
