name: Build and push to GHCR
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: swiszczoo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract frontend metadata
        id: meta_front
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/swiszczoo/chmura-frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Docker build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta_front.outputs.tags }}
          labels: ${{ steps.meta_front.outputs.labels }}

      - name: Extract backend metadata
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/swiszczoo/chmura-backend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Docker build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta_back.outputs.tags }}
          labels: ${{ steps.meta_back.outputs.labels }}

        